### ISSUE TITLE
JS IPFS Lite

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-textile#14]
A viable Textile Threads implementation in Javascript requires (at a minimum) Thread reading capabilities. This could be mostly done anonymously to begin with, and would therefore only require a minimal IPFS/Textile client. To accomplish this, we would need the equivalent of [`ipfs-lite`](https://github.com/hsanjuan/ipfs-lite) in Javascript. This Epic will be used to track progress on this project.

This will likely be a one-sprint Epic. The prior-art is already there, so the biggest challenge is creating the types, putting the components together, and then finishing the actual `ipfs-lite` implementation.

**Comment by Gozala** [comment]
I think it would be better to define the interface for the IO service that textile thread service will be passed. If it happens to be compatible with `ipfs-lite` and full blows `js-ipfs` even better. But defining what interface one needs to supply to get threads working is IMO better than coupling it with anythnig specific. For example I've done IPLD service that used dat for block exchange instead of IPFS and it was really empowering to have a choice in networking & storage layer.

**Comment by carsonfarmer** [comment]
100% this will all be interface driven, no coupling required. However, IPFS Lite is in line with other goals of ours, so that will be used as the reference implementation as we move forward.

**Comment by carsonfarmer** [comment]
P.S. js-ipfs-lite is already ready (for our needs) here: https://github.com/textileio/js-ipfs-lite

**Comment by carsonfarmer** [comment]
Done with https://github.com/textileio/js-ipfs-lite
